### ISSUE TITLE
Turbine skips item emissions

### ISSUE THREAD

**Issue by alterpie** [cashapp/turbine#113]
When using coroutines 1.6.1, Kotlin 1.6.21 and turbine 0.8.0, turbine skips emissions of items(issue was reported here #91 but for turbine version 0.7.0)

```kotlin
private val stateFlow = MutableStateFlow(0)
private val flow: Flow<Int> = stateFlow

@Test
fun `turbine test`() = runTest {
    Dispatchers.setMain(UnconfinedTestDispatcher())

    val scope = CoroutineScope(Job() + Dispatchers.Main)

    flow.test {
        flowOf(1, 2, 3)
            .onEach { stateFlow.value = it }
            .launchIn(scope)

        val events = cancelAndConsumeRemainingEvents()
    }

    Dispatchers.resetMain()
}
```

events will contain only the first and last items: ```[Item(0), Item(3)]``` instead of ```[Item(0), Item(1), Item(2), Item(3)]```

**Comment by JakeWharton** [comment]
I get the same results using a normal `collect` which means there is nothing Turbine can do here.

```kotlin
  private val stateFlow = MutableStateFlow(0)
  private val flow: Flow<Int> = stateFlow

  @Test
  fun `turbine test`() = runTest {
    Dispatchers.setMain(UnconfinedTestDispatcher())

    val scope = CoroutineScope(Job() + Dispatchers.Main)

    launch(start = UNDISPATCHED) {
      flow.collect {
        println(it)
      }
    }

    flowOf(1, 2, 3)
      .onEach { stateFlow.value = it }
      .launchIn(scope)

    Dispatchers.resetMain()
  }
```
```
0
3
```

**Comment by iRYO400** [comment]
@alterpie have you found a solution? just interesting
Isn't because of [StateFlow's behavior](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/)


> The value of mutable state flow can be updated by setting its value property. Updates to the value are always conflated. So a slow collector skips fast updates, but always collects the most recently emitted value.

**Comment by AlexDochioiu** [comment]
@iRYO400 there's some [workaround](https://github.com/Kotlin/kotlinx.coroutines/issues/3339) but so far it doesn't seem like they plan a reasonable way to collect conflated flows without missing emissions.
