### ISSUE TITLE
JS legacy support

### ISSUE THREAD

**Issue by whyoleg** [cashapp/turbine#133]
Hey, 0.9 doesn't contain support for  JS legacy. Is there a specific reason for this, like bugs?
I mean, turbine is useful at my side testing rsocket-kotlin multiplatform library, and as Legacy is till default JS target and still will be until kotlin 1.8 it would be good to support it

**Comment by JakeWharton** [comment]
Yes. It was almost dropped from 0.8 but I made it work at the last minute. However with 0.9 (and the next release that's coming) we are introducing more functionality where legacy JS does not work. Generally I've found this has to do with the use of coroutine timeouts, but it's not limited to that.

I would welcome a PR to restore legacy support! We simply don't have the time right now to chase down all the problems.

There's no harm in staying on an older version of the library is working for you today and you need to support legacy. While you won't get access to new APIs you also are guaranteed stability. At least, until you are comfortable dropping legacy from your library as well.

**Comment by whyoleg** [comment]
Thanks for info! Soon I will test new introduced API (looks promising) and check if it's will be ok for me to stay on 0.8, if not, I will try to create PR with restored legacy support :)

**Comment by JakeWharton** [comment]
#140 probably kills this completely. When I added similar functionality a few months ago it completely broke on JS legacy.

**Comment by whyoleg** [comment]
Let's then just close an issue. I had no time to investigate possibility to add legacy support here. And as from 1.8.0 looks like IR will be default and legacy/both will be deprecated it's safe and preferable to just move there. I also had some hacks to support legacy, so overall it will be better for all.
