### ISSUE TITLE
Issue with `awaitItem()`, `StateFlow` and 0.9.0 version

### ISSUE THREAD

**Issue by owolp** [cashapp/turbine#134]
I'm facing some issues when using `StateFlow` and upgrading to latest *0.9.0* version. Only the first and last items are received by `awaitItem()`.
Same tests pass on versions prior *0.9.0*. Tried *0.8.0* and *0.7.0*.

```kotlin
class FlowTest {

    private val mutableStateFlow = MutableStateFlow(0)
    val stateFlow = mutableStateFlow.asStateFlow()

    fun updateValues() {
        mutableStateFlow.update { 1 }
        mutableStateFlow.update { 2 }
        mutableStateFlow.update { 3 }
        mutableStateFlow.update { 4 }
        mutableStateFlow.update { 5 }
    }

    fun setValues() {
        mutableStateFlow.value = 1
        mutableStateFlow.value = 2
        mutableStateFlow.value = 3
        mutableStateFlow.value = 4
        mutableStateFlow.value = 5
    }
}

@ExperimentalCoroutinesApi
class FlowTestTest {

    @Test
    fun updateValues() = runTest {
        val sut = FlowTest()

        sut.stateFlow.test {
            sut.updateValues()

            assertEquals(0, awaitItem())
            assertEquals(1, awaitItem())
            assertEquals(2, awaitItem())
            assertEquals(3, awaitItem())
            assertEquals(4, awaitItem())
            assertEquals(5, awaitItem())
            assert(cancelAndConsumeRemainingEvents().isEmpty())
        }
    }

    @Test
    fun setValues() = runTest {
        val sut = FlowTest()

        sut.stateFlow.test {
            sut.setValues()

            assertEquals(0, awaitItem())
            assertEquals(1, awaitItem())
            assertEquals(2, awaitItem())
            assertEquals(3, awaitItem())
            assertEquals(4, awaitItem())
            assertEquals(5, awaitItem())
            assert(cancelAndConsumeRemainingEvents().isEmpty())
        }
    }

    @Test
    fun flowOfValues() = runTest {
        flowOf(0, 1, 2, 3, 4, 5).test {
            assertEquals(0, awaitItem())
            assertEquals(1, awaitItem())
            assertEquals(2, awaitItem())
            assertEquals(3, awaitItem())
            assertEquals(4, awaitItem())
            assertEquals(5, awaitItem())
            awaitComplete()
        }
    }
}
```

### Turbine 0.9.0
<img width="161" alt="image" src="https://user-images.githubusercontent.com/14075020/183075848-aed47ba5-4e31-4c92-9dca-75144c8de825.png">

<img width="728" alt="image" src="https://user-images.githubusercontent.com/14075020/183076558-b7e178ab-8a50-44d2-a54d-2704822ab803.png">

<img width="760" alt="image" src="https://user-images.githubusercontent.com/14075020/183076621-dfc19f7e-b71f-43a5-852b-4df953a56e20.png">

### Turbine 0.8.0, 0.7.0
<img width="164" alt="image" src="https://user-images.githubusercontent.com/14075020/183075930-8c647114-05a3-40fc-ba70-bdb3900a0ee4.png">

## Versions

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'app.cash.turbine:turbine:0.9.0'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4'

**Comment by Dimezis** [comment]
I'm surprised it worked before.

You're setting/updating items synchronously in a row and only then start calling `awaitItem`, which means it would land only on the default value `0` and the last item (`5` - as the tests show).
Unless the previous items are buffered, the current result is expected IMO.

**Comment by JakeWharton** [comment]
It looks like the use of `Unconfined` was removed in a refactoring which is likely the cause of the behavior change.

That being said, the whole point of `StateFlow` is that it reflects a state and not events. Seeing only 0 and 5 is valid. In general, if you have a `StateFlow`, you'll have much better luck doing simple assertions on `.value` rather than collecting it with a flow.

**Comment by owolp** [comment]
Thank you both for the explanation. I guess I've misused the functionality of the library.

For anyone interested on how I've fixed the above tests:

```kotlin
@Test
fun setValues090_1() = runTest {
    val values = mutableListOf<Int>()
    val sut = FlowTest()
    val job = launch(UnconfinedTestDispatcher(testScheduler)) {
        sut.stateFlow.toList(values)
    }

    sut.setValues()

    assertEquals(0, values[0])
    assertEquals(1, values[1])
    assertEquals(2, values[2])
    assertEquals(3, values[3])
    assertEquals(4, values[4])
    assertEquals(5, values[5])

    job.cancel()
}

// If using something like TestObserver, check links bellow
@Test
fun setValues090_2() = runTest {
    val sut = FlowTest()
    val test = sut.stateFlow.test(this)

    sut.setValues()

    test.assertValues(0, 1, 2, 3, 4, 5)
        .finish()

}
```

<img width="547" alt="image" src="https://user-images.githubusercontent.com/14075020/183504226-3c4650ce-0c28-4976-9891-e30e13596be3.png">

Read on:
- [Testing 1.6.0 - Correct way to collect and verify StateFlow<T> emissions ](https://github.com/Kotlin/kotlinx.coroutines/issues/3143)
- [From RxJava to Kotlin Flow: Testing](https://proandroiddev.com/from-rxjava-to-kotlin-flow-testing-42f1641d8433)
