### ISSUE TITLE
validation block is called before callbackFlow is created in 0.9.0

### ISSUE THREAD

**Issue by gabrielittner** [cashapp/turbine#136]
I have a component that I want to test that essentially creates a `callbackFlow` that should emit whenever a method on that component was called. A very simplified version of this would look like this:
```
runTest { // same for runBlocking
    val callbacks = mutableListOf<() -> Unit>()
    callbackFlow<Unit> {
        val callback = {}

        callbacks.add(callback)

        awaitClose {
            callbacks.remove(callback)
        }
    }.test {
        assertThat(callbacks.size).isEqualTo(1)

        // invoke callback and await items
    }
}
```
The test works before 0.9.0 but starting with that version it fails because the block passed to `callbackFlow` is executed after the assertion. I'm not sure if this was an intentional behavior change or not

**Comment by JakeWharton** [comment]
Can't look until after Droidcon NYC, sorry. Someone else will have to.

**Comment by JakeWharton** [comment]
This test passes:
```kotlin
  @Test fun test() = runTest {
    var called = false
    flow<Nothing> {
      called = true
      suspendCancellableCoroutine {  }
    }.test {
      assertEquals(true, called)
      cancel()
    }
  }
```
When I change to `callbackFlow` (and delete the infinite suspension) it fails. Therefore the problem is upstream in the kotlinx.coroutines library and how it dispatches to the lambda when `callbackFlow` is used. There's nothing we can do to affect the behavior.
