### ISSUE TITLE
Different behaviour of `expectNoEvents()` method between versions `0.8.0` and `0.9.0` when testing `MutableStateFlow`

### ISSUE THREAD

**Issue by pawelostafin** [cashapp/turbine#138]
It seems that version `0.9.0` changed behaviour of `expectNoEvents()` method.

```
@Test
fun booleanFlowTest() = runTest {
    val booleanFlow = MutableStateFlow(false)
    booleanFlow.test {
        assertEquals(false, awaitItem())
        booleanFlow.value = true
        expectNoEvents()
    }
}
```

`0.8.0` -> test fails with `app.cash.turbine.AssertionError: Expected no events but found Item(true)` (which is correct behaviour)
`0.9.0` -> test passes

What is even weirder, using deprecated method `runBlockingTest` when testing with version `0.9.0` results in correct behaviour.

**Comment by JakeWharton** [comment]
It fails because we lost the use of the `Unconfined` dispatcher to record emissions into our internal channel synchronously. Unfortunately, the use of `Unconfined` also breaks `runTest` usage.

**Comment by zsmb13** [comment]
Another simple test case that produces the same issue across these versions:

```kotlin
@Test
fun useTurbineForCollection() = runTest {
    val stateFlow = MutableStateFlow(0)

    launch {
        stateFlow.test {
            assertEquals(0, awaitItem())
            assertEquals(1, awaitItem()) // Already gets "3" in Turbine 0.9.0
            assertEquals(2, awaitItem())
            assertEquals(3, awaitItem())
        }
    }

    launch {
        stateFlow.value = 1
        stateFlow.value = 2
        stateFlow.value = 3
    }
}
```
