### ISSUE TITLE
`cancelAndIgnoreRemainingEvents()` does not cancel a Molecule StateFlow

### ISSUE THREAD

**Issue by Egorand** [cashapp/turbine#139]
This might be Molecule-specific, but I still expect `cancelAndIgnoreRemainingEvents()` to be able to cancel any `StateFlow`. 

Here's a simple Molecule presenter:

```kotlin
@Composable fun MoleculePresenter(): Model {
  return Model("Hello!")
}
```

And a test for it:

```kotlin
class MoleculePresenterTest {
  @Test fun test() = runBlocking {
    makePresenter().test {
      assertEquals(Model("Hello!"), awaitItem())
      cancelAndIgnoreRemainingEvents()
    }
  }

  private fun CoroutineScope.makePresenter(): StateFlow<Model> {
    return launchMolecule(RecompositionClock.Immediate) {
      MoleculePresenter()
    }
  }
}
```

`test()` never completes when executed, neither with `cancelAndIgnoreRemainingEvents()` nor without it.

The repro project is here: https://github.com/Egorand/turbine-cancel-hangs. Simply run `./gradlew app:testDebugUnitTest` to reproduce the issue.

(Crappy) workaround:

```kotlin
@Test(expected = CancellationException::class)
fun test() = runBlocking {
  makePresenter().test {
    assertEquals(Model("Hello!"), awaitItem())
    coroutineContext.cancel()
  }
}
```

**Comment by JakeWharton** [comment]
As far as Turbine is concerned, this is working as expected. The coroutine which is driving the `StateFlow` was launched separately from Turbine's own coroutine which collects from the `StateFlow`. When you cancel, Turbine can only cancel the one which is doing the collection.

You would see similar behavior with code like:
```kotlin
val flow = neverFlow().stateIn(this, Unit)
flow.test { cancelAndIgnoreRemainingEvents() }
```

If you launch any coroutines separately from Turbine they will also need to be canceled at the end of the test. You can do this by canceling all children of the `runBlocking` scope, or starting a child scope with an explicit `Job` that you can cancel, or, in this case, by switching to a `moleculeFlow` instead of `launchMolecule`.

**Comment by PaulWoitaschek** [comment]
In my pet project I overcame this by using `runTest` in combination with the background dispatcher:
https://github.com/PaulWoitaschek/Voice/blob/4625edbc891327bfa15aff3641b78c153d9444ed/folderPicker/src/test/kotlin/voice/folderPicker/selectType/SelectFolderTypeViewModelTest.kt#L38

**Comment by JakeWharton** [comment]
Nice! Can you contribute something to the README about that pattern?

**Comment by PaulWoitaschek** [comment]
About which pattern? Utilizing molecule + turbine to test composables?

**Comment by JakeWharton** [comment]
A bit more general in that the background scope can be used for launching things which produce a `StateFlow` which become the subject of a Turbine test.

Although, in general, testing a `StateFlow` with Turbine (at least with 0.9.0) is a bit sketchy. We no longer use the `Unconfined` dispatcher for collections so you are subject to races with which actual states you see reflected as events. Ideally you can just call `.value` after performing an action, but that relies on no threading to be in play. If there is threading at play, `awaitItem()` may conflate two updates into a single event which can surprise.

So I'm not actually sure how detailed we want to get here.

**Comment by Egorand** [comment]
Gonna close the issue cause it's not really a bug.
