### ISSUE TITLE
GH releases do not have binaries attached

### ISSUE THREAD

**Issue by MiSikora** [cashapp/turbine#14]
`github-release` is a separate job from the `publish` job. When binaries are collected by `action-gh-release` step they are not present in the directory.

https://github.com/cashapp/turbine/blob/39740b4dad4977de427e1bf43121570ad0f2a618/.github/workflows/release.yaml#L54-L58

https://github.com/cashapp/turbine/runs/1024853027?check_suite_focus=true#step:5:10

Since `github-release` job needs `publish` anyway they could be merged into a one job. This is just a suggestion as I don't know if there is a better way to do this.

On the side note, it would be nice to add binaries to already published GH releases retroactively.

**Comment by JakeWharton** [comment]
> Since github-release job needs publish anyway they could be merged into a one job.

For nonsensical reasons the `ffurrer2/extract-release-notes` step only runs on Linux.

Because we need to build binaries on multiple platforms we would have to cache those artifacts from the Mac and Windows workers and then upload them from Linux. I'd take a PR to do this. Unfortunately it's going to be relatively low priority for me to fix.

The artifacts are all available here if you need them for now: https://repo1.maven.org/maven2/app/cash/turbine/

**Comment by MiSikora** [comment]
> For nonsensical reasons the ffurrer2/extract-release-notes step only runs on Linux.

Ahh, got it. That's a bummer.

I think I'll make a contribution to the step instead of making a workaround here. I guess this issue can be kept open until fix lands in the step or someone takes care of caching.

**Comment by MiSikora** [comment]
Latest release [`v1.4.0-rc1`](https://github.com/ffurrer2/extract-release-notes/releases/tag/v1.4.0-rc.1) supports different platforms. I can make a PR with the change. Do you want to publish all binaries contained in the `build/libs/*` or do you want to exclude i.e. sources jar?

**Comment by JakeWharton** [comment]
We don't pay for the hosting, so might as well just do everything.

**Comment by JakeWharton** [comment]
Closing this since I don't think it's high priority or essential.

**Comment by MiSikora** [comment]
Yeah, sorry for the radio silence. I attempted to do it but failed horribly at extracting native binaries in some sane way.

**Comment by JakeWharton** [comment]
Yeah I know it's a lot harder, and I'm not sure it's actually useful for someone to use.
