### ISSUE TITLE
Regression: Testing MutableSharedFlow(extraBufferCapacity = 1) + flatMapLatest + tryEmit results in awaitItem() timeout

### ISSUE THREAD

**Issue by mhernand40** [cashapp/turbine#148]
The following test passes on `0.8.0` but fails on `0.9.0` due to a timeout with `awaitItem()`:

```Kotlin
  @Test
  fun repro() = runTest(dispatchTimeoutMs = 100L) {
    val sharedFlow = MutableSharedFlow<Int>(extraBufferCapacity = 1)
    sharedFlow
        .flatMapLatest { value -> flowOf(value) }
        .test {
          sharedFlow.tryEmit(1)
          assertThat(awaitItem()).isEqualTo(1)
        }
  }
```

Observations:
* Test passes when using `flatMapConcat` instead of `flatMapLatest`
* Test passes if `replay = 1` is used instead of `extraBufferCapacity = 1`.
* Test passes if `runTest(UnconfinedTestDispatcher())` is used.
* Test still fails if `sharedFlow.emit(1)` is used instead of `sharedFlow.tryEmit(1)`.

I'm using Kotlin `1.7.10` and Coroutines `1.6.4`.

**Comment by JakeWharton** [comment]
This test:
```kotlin
  @Test fun repro() = runTest(dispatchTimeoutMs = 100) {
    val sharedFlow = MutableSharedFlow<Int>(extraBufferCapacity = 1)
    lateinit var job: Job
    job = launch(start = UNDISPATCHED) {
      sharedFlow
        .flatMapLatest { flowOf(it) }
        .collect {
          println(it)
          job.cancel()
          println("cancel")
        }
    }
    sharedFlow.tryEmit(1)
    println("after tryEmit")
  }
```
Fails to complete successfully. It never prints "1".

If you comment out the `flatMapLatest` line, it completes successfully and both "1" and "cancel" are printed.

Turbine, at its core, just calls `collect` on a `Flow`. If it cannot collect the upstream `Flow` then it cannot produce values. I don't see how there is anything we can do here. If you believe this is a bug (I've never used a shared flow) then I would recommend filing a bug upstream on kotlinx.coroutines.

**Comment by mhernand40** [comment]
I'm assuming the reason the test passed with version `0.8.0` is because Turbine was internally launching its collector with `Dispatchers.UNCONFINED`? This may explain why the test also passes with `runTest(UnconfinedTestDispatcher())`.

**Comment by JakeWharton** [comment]
I tested on `trunk` where `Unconfined` has been restored and it still failed for me (both your version and my version).

**Comment by JakeWharton** [comment]
Nevermind I forgot to pull `trunk` before testing. Your test passes on the latest. So this is a dupe of #138.

**Comment by mhernand40** [comment]
The snippet I pasted in the Issue Summary is a dumbed down version of a scenario one of my team project's tests was running. I have confirmed that with `0.10.0` the test now passes. 👍
