### ISSUE TITLE
Behavior Change: runTest + testing Flow with infinite loop causes advanceUntilIdle() to hang

### ISSUE THREAD

**Issue by mhernand40** [cashapp/turbine#155]
Perhaps this is expected behavior but after updating to `0.11.0`, one of the tests in my team project are now hanging forever. The test never fails with a timeout. I have reduced it down to the following repro:
```Kotlin
class Repro {

  private val flow = flow<String> {
    while (true) {
      delay(100L)
    }
  }

  @Test
  fun repro() = runTest {
    flow.test {
      advanceUntilIdle() // Hangs here forever with version 0.11.0
      expectNoEvents()
    }
  }
}
```

With `0.10.0` this test passes immediately.

**Comment by JakeWharton** [comment]
I believe the new behavior is now correct per the `advanceUntilIdle` docs. Your flow never idles. You should see the same behavior without using Turbine by doing a `launch(UNDISPATCHED) { flow.collect { } }` and then invoking `advanceUntilIdle()`.

It's almost impossible to test this kind of case. There is always the chance that if you advance one more millisecond you would see an event. The best you can do is delay for a couple days/weeks/years and assert no event occurred.

**Comment by mhernand40** [comment]
Thank you for the response. I suspected this behavior change was by design and probably more correct. I'll update the hanging test accordingly. Thanks again!
