### ISSUE TITLE
test re-throws Throwable instead of wrapping it in an Event.Error

### ISSUE THREAD

**Issue by drymarau** [cashapp/turbine#159]
The behavior seems to have changed between 0.8.0 and 0.9.0 (also reproducible in 0.11.0).

The following test works correctly:
https://github.com/cashapp/turbine/blob/6bb1e72f03a0e21aa39d0063081c5d5f107c16f9/src/commonTest/kotlin/app/cash/turbine/FlowTest.kt#L350-L355

But if we substitute `CustomRuntimeException` with a `CustomThrowable` this test will no longer passes and `test { }` will re-throw `CustomThrowable` instead:

```kotlin
internal class CustomThrowable(
  message: String?,
  override val cause: Throwable? = null,
) : Throwable(message)

@Test fun expectErrorWithThrowable() = runTest {
  val error = CustomThrowable("hi")
  flow<Nothing> { throw error }.test {
    assertSame(error, awaitError())
  }
}
```

It seems that `ReceiveChannel<T>.awaitEvent()` is missing `catch (t: Throwable)` clause which causes this issue:
https://github.com/cashapp/turbine/blob/6bb1e72f03a0e21aa39d0063081c5d5f107c16f9/src/commonMain/kotlin/app/cash/turbine/channel.kt#L74-L98

Adding the clause and modifying `Flow<T>.collectIntoChannel()` to catch `Throwable` instead of `Exception` lets the test complete successfully.

Is this behavior change intentional?

**Comment by JakeWharton** [comment]
No. It is a regression.
