### ISSUE TITLE
Is this the intended use with StateFlow?

### ISSUE THREAD

**Issue by himattm** [cashapp/turbine#19]
Recently I used turbine to test some StateFlow's and came across a particular interaction and I'm mostly wondering what is the intended use. Both of the below cases fail.

```kotlin
oven.preWarm(300)
oven.states.test { state ->
  assertEquals(WARMING(100), expectItem())
  assertEquals(WARMING(200), expectItem())
  assertEquals(PREWARM_COMPLETE, expectItem())

  cancelAndIgnoreRemainingEvents()
}
```
For this case calling `expectItem()` only receives the final state expected (PREWARM_COMPLETE) from the `preWarm()` call and will fail the assertions. This makes sense as the collect operator is starting when our StateFlow has already emitted up to this state.

```kotlin
oven.states.test { state ->
  assertEquals(WARMING(100), expectItem())
  assertEquals(WARMING(200), expectItem())
  assertEquals(PREWARM_COMPLETE, expectItem())

  cancelAndIgnoreRemainingEvents()
}

oven.preWarm(300)
```
For this case there is an exception for a default `timeout`:
 `kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 1000 ms` 

or for `timeout = Duration.ZERO`
 `java.lang.IllegalStateException: This job has not completed yet`

<hr />

However, when used like the below, moving the call to trigger state emission to the `validate` lambda, all expected events are received and the test passes. This is because `validate` is called after collection starts on the receiver flow.

```kotlin
oven.states.test { state ->
  oven.preWarm(300)
  assertEquals(WARMING(100), expectItem())
  assertEquals(WARMING(200), expectItem())
  assertEquals(PREWARM_COMPLETE, expectItem())

  cancelAndIgnoreRemainingEvents()
}
```

And also launching in a new job and calling test and the emission after succeeds as well.
```kotlin
launch {
  oven.states.test { state ->
    assertEquals(WARMING(100), expectItem())
    assertEquals(WARMING(200), expectItem())
    assertEquals(PREWARM_COMPLETE, expectItem())

    cancelAndIgnoreRemainingEvents()
  }

  oven.preWarm(300)
}
```

The documentation provided so far doesn't provide much information for a best practice on how to handle Flows that have their emissions triggered elsewhere. What is the best practice here? I would assume that launching a new job should not be required.

<hr />

Note: I am using this rule to `runBlockingTests`

```kotlin
@ExperimentalCoroutinesApi
class MainCoroutineRule(
    val testDispatcher: TestCoroutineDispatcher = TestCoroutineDispatcher(),
) : TestWatcher() {

    override fun starting(description: Description?) {
        super.starting(description)
        Dispatchers.setMain(testDispatcher)
    }

    override fun finished(description: Description?) {
        super.finished(description)
        Dispatchers.resetMain()
        testDispatcher.cleanupTestCoroutines()
    }

    /**
     * A convenience function to prevent the need to call a long chain for the provided dispatcher
     */
    fun runBlockingTest(block: suspend TestCoroutineScope.() -> Unit) {
        testDispatcher.runBlockingTest { block() }
    }
}
```

**Comment by himattm** [comment]
After a bit more perusing I found the test for this scenario where a `launch` _is_ used 

https://github.com/cashapp/turbine/blob/794b7ab1bca115351deb6ec5e9b18655c59b9bb8/src/commonTest/kotlin/app/cash/turbine/FlowTurbineTest.kt#L365-L388

Would this be the best practice then?

**Comment by JakeWharton** [comment]
The version which calls `preWarm` inside of the `test` block is what I would recommend here and in general. The lifetime of the lambda which is passed to `test` is the lifetime of the collection of the upstream flow. Any side-effects that you need to trigger should be done inside the lambda so that they can be observed.

I can try to find a way to talk about this more clearly in the README or somewhere because I can see it not being entirely obvious how you write tests with side-effects that are needed to trigger events.

**Comment by himattm** [comment]
Good to know, thank you!

**Comment by yusufceylan** [comment]
@matthewcmckenna What does `preWarm` do? I am trying to test my `StateFlow` but a little bit confused

I want to test this method with Turbine

```
    private fun fetchPosts() {
        viewModelScope.launch {
            postsUseCase.execute(null)
                .onStart { emit(Resource.Loading) }
                .collect {
                    when (it) {
                        is Resource.Loading -> {
                            // Set State
                            setState { copy(postsState = MainContract.PostsState.Loading) }
                        }
                        is Resource.Empty -> {
                            // Set State
                            setState { copy(postsState = MainContract.PostsState.Idle) }
                        }
                        is Resource.Success -> {
                            // Set State
                            val posts = postMapper.fromList(it.data)
                            setState { copy(postsState = MainContract.PostsState.Success(posts = posts)) }
                        }
                        is Resource.Error -> {
                            // Set Effect
                            setEffect { MainContract.Effect.ShowError(message = it.exception.message) }
                        }
                    }
                }
        }
    }
```

I expected that first item is `Resource.Loading` and second item is `Resource.Success`. But only receives the final state. It skips the first loading emission. When I debug, I see that `onStart` has been called in the method above. Is my approach wrong or am I missing something?

```
    @Test
    fun test_fetch_posts_success() = runBlockingTest {

        val posts = TestDataGenerator.generatePosts()
        val postFlow = flowOf(Resource.Success(posts))

        // Given
        coEvery { postUseCase.execute(null) } returns postFlow

        // When && Assertions
        mainViewModel.setEvent(MainContract.Event.OnFetchPosts)
        mainViewModel.uiState.test {
            // Expect Resource.Loading
            Truth.assertThat(expectItem()).isEqualTo(
                MainContract.State(
                    postsState = MainContract.PostsState.Loading,
                    selectedPost = null
                )
            )
            // Expect Resource.Success
            Truth.assertThat(expectItem()).isEqualTo(
                MainContract.State(
                    postsState = MainContract.PostsState.Success(postMapper.fromList(posts)),
                    selectedPost = null
                )
            )
            cancelAndIgnoreRemainingEvents()
        }


        // Then
        coVerify { postUseCase.execute(null) }
    }
```

**Comment by himattm** [comment]
@yusufceylan `prewarm` in this example it would be something like:

```kotlin
fun preWarm(val targetTemp: Int) {
  var temp = 0
  while (temp <= targetTemp) {
    _states.value = WARMING(temp)
    temp += 100
  }

  _states.value = PREWARM_COMPLETE
}
```

Where the `StateFlow`s value is being changed outside of the collection, and the collection is being used to provide the states to observers.

For your problem though, it looks like your `val postFlow = flowOf(Resource.Success(posts))` only contains the `Resource.Success` state from your mock. You'll need to change that to emit the expected results or use an actual implementation of the class containing `fetchPosts`.

**Comment by yusufceylan** [comment]
Thanks for your answer @matthewcmckenna I changed `postFlow` to

```
        val postFlow = flow {
            emit(Resource.Loading)
            emit(Resource.Success(posts))
        }
```
and still same.  I think, I miss something different because when I changed the `test { }` with `collect { }` for test purpose and figured out that, it behaves same (still only emit last item).

**Comment by himattm** [comment]
@yusufceylan What is ` mainViewModel.uiState`?

and what does `setState { }` do?

**Comment by yusufceylan** [comment]
It is simple `StateFlow`

```
    private val _uiState : MutableStateFlow<State> = MutableStateFlow(initialState)
    val uiState = _uiState.asStateFlow()
```
and `setState` change the state

```
    protected fun setState(reduce: State.() -> State) {
        val newState = currentState.reduce()
        _uiState.value = newState
    }
```

**Comment by himattm** [comment]
@yusufceylan  I assume when you call `mainViewModel.setEvent(MainContract.Event.OnFetchPosts)` it calls to `fetchPosts`. This is being done outside of the `.test` scope so I think that Flow is running through all of its events in a different scope so when you get to the `.test` scope your Flow is already on its last expected event. You will probably have to change this to be emitting your events within the `.test` scope just as I did in the third code block in the original post.

Another suggestion, you should probably test the `postsUseCase.execute(null)` Flow instead of the `uiState` Flow for this test. That might simplfy some of these scoping issues. Then create a function that takes the `Resource` and does the logic in that `collect` call. Then you can test that new function for each type of `Resource` without needing the `uiState` Flow.

**Comment by yusufceylan** [comment]
You are right @matthewcmckenna . As you suggested I moved `mainViewModel.setEvent(MainContract.Event.OnFetchPosts)` inside the `.test` block and now I can retrieve all emitted events. 

I also wrote tests for `usecases` in my domain layer with Flow. It is super easy to test with Turbine :) now I want to test my `ViewModels` and `uiStates` with `StateFlows`. Thanks to you it works now

**Comment by spiral123** [comment]
@matthewcmckenna  @yusufceylan Thanks for your comments: I was tearing my hair out trying to get my `StateFlow` tests to work.

This library is super-useful...it's even possible to write fluent tests:

```
    @Test
    fun `verify resetArtistData emits an empty list to artistData`() {
        mockWebServer.enqueueResponse("artist_data_3_tracks.json", HttpURLConnection.HTTP_OK)

        runBlocking {
            sut.artistData.test {
                // initial state
                assertEquals(ArtistDataState.Success(emptyList()), expectItem())

                sut.loadArtistData("osijfdsdoi")
                assertEquals(ArtistDataState.Loading, expectItem())
                assertEquals(3, (expectItem() as ArtistDataState.Success).data.size)

                sut.resetArtistData()
                assertEquals(0, (expectItem() as ArtistDataState.Success).data.size)

                cancelAndIgnoreRemainingEvents()
            }
        }
    }
```

**Comment by osrl** [comment]
When I use `runBlocking` instead of `runBlockingTest` I don't get TimeoutCancellationException. 

```
fun test() = runBlocking {

        myUseCase.myStateFlow.test {
            assertEquals(ResponseState.Loading, expectItem())
            assertTrue(expectItem() is ResponseState.Success)
        }

    }
```
Replacing `runBlocking` with `runBlockingTest` throws the exception. 

Should I always use runBlocking?

**Comment by himattm** [comment]
@osrl Depending on your implementation that could be okay. `runBlockingTest` has added control for the execution of a coroutine which you might not need. You can see those features [here](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/).

**Comment by kotya341** [comment]
`runBlockingTest` is now deprecated, is there a good way to migrate to `runTest`?

**Comment by mhernand40** [comment]
> `runBlockingTest` is now deprecated, is there a good way to migrate to `runTest`?

@kotya341 From my experience, it was not a very straightforward migration. JetBrains has a migration doc for this:
* https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md

I found that a lot of our `runBlockingTest` calls had to be migrated to `runTest(UnconfinedTestDispatcher())` in order for many of the tests to continue working without any further changes. That was enough to at least get us to migrate to Coroutines 1.6.0. But after that, I would encourage migrating the tests to just basic `runTest` if possible.
