### ISSUE TITLE
0.11.0 Timeout enhancement can make tests flaky

### ISSUE THREAD

**Issue by trevjonez** [cashapp/turbine#199]
I was just updating from 0.9.0 to the latest and had some tests that would flake out when running our entire unit test suite the way CI does.

Basically the issue is that if the CPU load of the host is high the tests can take longer to run and thus hit the default timeout of 1 second.

In the short term I just adjusted my Gradle config to not fork the test runner thus artificially keeping CPU utilization lower while running tests by forcing them to run serially in a given sub project. BUT things that make good use of a multi core system like the kotlin compiler could probably trigger the issue in a hard to repeat manner as well.

So I wonder can/should we make the default timeout longer to add some headroom for test runtime variance caused by a loaded down system? Something more like 5 or 10 seconds maybe?

Adding the `timeout` param to the `test` calls that failed under load is doable but feels sort of dirty.

As I typed this all out, this question comes to mind:
Given that junit4 has `@Test(timeout = 42)` and jupiter has `@Timeout` to stop a likely deadlocked test, should turbine even have an on by default timeout?

**Comment by JakeWharton** [comment]
> Given that junit4 has `@Test(timeout = 42)` and jupiter has `@Timeout` to stop a likely deadlocked test, should turbine even have an on by default timeout?

Both of these are opt-in and rarely used (or maybe oft forgotten is a better classification).

I'm no fan of our timeouts. They're changing `runTest` to have a default wall clock timeout of something like 10 seconds. This is different than the current behavior which is no coroutines scheduled in 60 seconds. Maybe then we can eliminate the use of our own timeouts (aside from explicitly wanting to test timeout behavior).

If you just want to make the default timeout slightly higher feel free to send a PR. I would not go above 5 seconds, though.
