### ISSUE TITLE
Unexpected item received

### ISSUE THREAD

**Issue by sebastianharder** [cashapp/turbine#20]
Hi,

I am a bit lost with a test that keeps failing, no matter how I change it. I test a flow which should emit only models that are in an "existing" state:

    testModel.existingFlow().onEach { println("Flow contains $it") }.test {
        for (modelState in allModelStates) {
            testModel.nextModelState = modelState
            testModel.listener.onModelChanged(testModel) // invoke flow emission
            if (modelState.exists()) {
                expectItem()
            } else {
                expectNoEvents() // AssertionError
            }
        }
        cancel()
    }

The log prints like this:

    Flow contains TestModel{state=SYNCHRONIZED, exists=true}
    Flow contains TestModel{state=OUT_DATED, exists=true}
    Flow contains TestModel{state=UPDATING, exists=true}
    Flow contains TestModel{state=CREATING, exists=true}
    
    app.cash.turbine.AssertionError: Expected no events but found Item(TestModel{state=DELETED, exists=false})

So, as you can see, the flow has emitted only the states that are considered as "existing", but somehow another item with state "DELETED" is received by the Turbine Flow.

By the way, thanks a lot for this great library! It makes testing flows so much more beautiful.

Turbine: 0.3.0
Kotlin: 1.4.21
Coroutines: 1.4.2

**Comment by JakeWharton** [comment]
Thanks for the report. I will have to try to find time to reproduce. Can you show how your view model is built? Are you using StateFlow?

**Comment by sebastianharder** [comment]
It's actually a data model that one can register a listener on and receive changes. I wrapped this in a `callbackFlow`:

    @ExperimentalCoroutinesApi
    fun <M : Model<M, D?>, D : ModelData> Model<M, D?>.existingFlow(): Flow<M> = callbackFlow {
        val listener = ModelListener<M, D?> { model -> offer(model) }
        registerModelListener(listener)
        awaitClose { unregisterModelListener(listener) }
    }.filter { it.state.exists() }

The `TestModel` looks like this:

    class TestModel : Model<TestModel, TestDataModel?> {
      var nextData: TestDataModel? = TestDataModel()
      lateinit var nextModelState: ModelState
      var listener: ModelListener<TestModel, TestDataModel?>? = null
          
      override fun registerModelListener(listener: ModelListener<TestModel, TestDataModel?>) {
          this.listener = listener
          this.listener?.onModelChanged(this)
      }
      
      override fun unregisterModelListener(listener: ModelListener<TestModel, TestDataModel?>) {
          this.listener = null
      }
      
      override fun getState(): ModelState = nextModelState
      
      override fun toString(): String = "TestModel{state=$state, exists=${state.exists()}}"
    }

**Comment by JakeWharton** [comment]
Have you simplified the example? Your `filter` is checking `it.state.exists` but the output shows the boolean is directly on the model as `it.exists`.

This test passes:
```kotlin
  enum class State {
    SYNCHRONIZED,
    OUT_DATED,
    UPDATING,
    CREATED,
    DELETED,
  }

  data class TestModel(
    val state: State,
    val exists: Boolean,
  )

  @Test fun issue20() = runBlocking {
    val allModelStates = listOf(
      TestModel(State.SYNCHRONIZED, true),
      TestModel(State.OUT_DATED, true),
      TestModel(State.UPDATING, true),
      TestModel(State.CREATED, true),
      TestModel(State.DELETED, false),
    )

    lateinit var producer: ProducerScope<TestModel>
    callbackFlow<TestModel> {
      producer = this
      awaitClose { }
    }.filter { it.exists }.test {
      for (modelState in allModelStates) {
        producer.send(modelState)
        if (modelState.exists) {
          expectItem()
        } else {
          expectNoEvents()
        }
      }
      producer.close()
      expectComplete()
    }
  }
```

**Comment by sebastianharder** [comment]
Now I found the issue. The call to `registerModelListener` already calls the listener itself, which causes an initial flow emission, so that `expectItem` always returns the previous flow emission instead of the currently expected one. The strange log output is due to the mutable nature of the test model then, which caused the whole confusion on my side.

Sorry for wasting your time!
