### ISSUE TITLE
expectNoEvents eats exceptions thrown by flows

### ISSUE THREAD

**Issue by matejdro** [cashapp/turbine#205]
Following test:

```kotlin
@Test
fun `Fail when flow throws and we expect no events`() = runTest {
   val flowThatThrows = flow<Nothing> {
      throw IllegalStateException()
   }

   assertThrows<Throwable> {
      flowThatThrows.test {
         expectNoEvents()
      }
   }
}
```

## Expected behavior

`expectNoEvents()` should throw an exception, since there WAS an event (a thrown exception).

## Actual Behavior

`expectNoEvents()` ignores the thrown exception and thus this test fails because no exception was thrown.

This is with coroutines 1.6.4 and turbine 0.12.1.

**Comment by jingibus** [comment]
Looks like the bug is here:

```kotlin
public fun <T> ReceiveChannel<T>.expectNoEvents(name: String? = null) {
  val result = tryReceive()
  if (!result.isFailure) result.unexpectedResult(name, "no events")
}
```

`result.isFailure` is true, but in this scenario doesn't indicate "We didn't receive anything" — it indicates the channel is closed.
