### ISSUE TITLE
TimeoutCancellationException is not catched

### ISSUE THREAD

**Issue by jeantuffier** [cashapp/turbine#208]
Snippet to replicate the issue
```
@Test
fun shouldTimeOut() = runTest {
    suspend fun number(): Int {
        delay(2000)
        return 1
    }

    flow {
        emit(0)
        withTimeout(1000) {
            emit(number())
        }
    }.test(3.seconds) {
        assertEquals(0, awaitItem())
        assertTrue(awaitError() is TimeoutCancellationException)
    }
}
```
Expected : the test passes.
Actual : the test fails with `No value produced in 3s`

(Original slack message for a bit more context : https://kotlinlang.slack.com/archives/C5HT9AL7Q/p1680097861931639)

**Comment by JakeWharton** [comment]
We think this is conflating our wall-clock timeout with a timeout that comes through the flow but haven't confirmed.

**Comment by jingibus** [comment]
Confirmed. It's our usage of `receive()` within a `withTimeout`; we can't distinguish cancellations across the two calls.
