### ISSUE TITLE
List dependency updates in (0.13.0) changelog(s)

### ISSUE THREAD

**Issue by G00fY2** [cashapp/turbine#228]
In Turbine 0.13.0 Coroutines [1.6.4](https://github.com/cashapp/turbine/blob/924bb5346408c3f03d391b5558b7d5f1b2b3cdd4/build.gradle#L14) was updated to [1.7.0](https://github.com/cashapp/turbine/blob/f14611a33bf31920843b8f992a2a1ad7b19e5e36/gradle/libs.versions.toml#L2).

This is directly affecting consumers, because of how Gradles transitive dependency resolution works. Therefore this dependency bump should be part of the changelog.

PS: Coroutines 1.7.0 currently has some [blocking issues](https://github.com/Kotlin/kotlinx.coroutines/issues/3673) for Android devs which may prevent them from migrating.

**Comment by JakeWharton** [comment]
Added:

> Note: This version has a transitive dependency on kotlinx.coroutines 1.7.0. If you are an Android user, you should be depending on kotlinx.coroutines 1.7.1 which graciously fixes a binary incompatibility with a Compose testing artifact (because they failed to heed its opt-in annotation which indicated that it was not a stable API).

**Comment by JakeWharton** [comment]
We were tracking the issue, but thanks for the reminder to spread it more widely.
