### ISSUE TITLE
AdvanceTimeBy has no effect - because `delay` is being ignored, maybe...

### ISSUE THREAD

**Issue by mylesbennett** [cashapp/turbine#265]
This is likely to be a setup thing on my part so probably my issue, not yours
I was having the same problem as [this](https://github.com/cashapp/turbine/issues/42 ) using v0.6.1.
I upgraded to 1.0.0 and now I have the opposite problem:- I can't test for a specific delay.
The following should fail, but it passes:
```
    @Test
    fun `test synchronous flow emission using Turbine`() = runTest {
        val flow = flow {
            emit(1)
            delay(100)
            emit(2)
        }

        flow.test {
            assertEquals(1, awaitItem())
//            advanceTimeBy(101)
            assertEquals(2, awaitItem())
            awaitComplete()
        }
    }
```
Notice commented out `advanceTimeBy`
Conversely, a similar test in the same environment without Turbine (successfully?) fails:
```
    @Test
    fun `test synchronous flow emission without Turbine`() = runTest {
        val flow = flow {
            emit(1)
            delay(100)
            emit(2)
        }

        val collectedValues = mutableListOf<Int>()
        launch {
            flow.collect { value ->
                collectedValues.add(value)
            }
        }

//        advanceTimeBy(101)
        assertEquals(listOf(1, 2), collectedValues)
    }
```
How do I set up dispatchers, etc. so that I get the same result with Turbine?

**Comment by JakeWharton** [comment]
The way to test for a delay is to advance 1 millisecond before the delay ends, assert no events have been received, and then advance the final millisecond (or simply call await which will skip the remainder).

The behavior of delay skipping is documented on `runTest`: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-test.html

> On JVM and Native, this function behaves similarly to runBlocking, with the difference that the code that it runs will skip delays.
> ...
> On JS, this function creates a Promise that executes the test body with the delay-skipping behavior.

**Comment by mylesbennett** [comment]
Thanks for your suggestion. I totally agree.
In fact, this was just a minimal example to show up the issue rather than a bonafide product code test.

I have identified the issue so I'll be closing this. In this minimal example, I should be using `expectMostRecentItem()` in place of both the `awaitItem()` statements, then the test behaves as expected.

The documentation is a little foggy:-

**expectMostRecentItem()**
_"Returns the most recent item that has already been received..."_

**awaitItem()**
_"Assert that the next event received was an item and return it..."_
