### ISSUE TITLE
javadocs are empy

### ISSUE THREAD

**Issue by StefMa** [cashapp/turbine#280]
If I see it right, the javadocs.jar at [maven central](https://repo1.maven.org/maven2/app/cash/turbine/) "are empty".
They include only a `META-INF` directory, including a `MANIFEST.MF` file which is kinda of empty 😁 
I checked `turbine-js`, `turbine-macosarm63` and `turbine-jvm`.

If I see it corectly, we can add the correct javadoc simply by using:
```kotlin
mavenPublishing {
  configure(new KotlinMultiplatform(new JavadocJar.Dokka("dokkaHtml")))
}
```
See also https://vanniktech.github.io/gradle-maven-publish-plugin/base/#kotlin-multiplatform-library

Or are there any reasons not publish the javadocs? 🙃

**Comment by StefMa** [comment]
Alright, tested it out and I run into this one 😭 
https://github.com/vanniktech/gradle-maven-publish-plugin/issues/624

**Comment by StefMa** [comment]
Alright, I found the problem.
The problem is in the nexus plugin (0.25.3).
Basically it behaves as the following:
* It checks if the Kotlin Multiplatform plugin will be applied ([see](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/cfd2a0d6a37304cfd90b2631d188e76dd0dccbae/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishPlugin.kt#L35-L37))
* As soon as it got applied, it checks if the dokka plugin **is** applied (https://github.com/vanniktech/gradle-maven-publish-plugin/blob/cfd2a0d6a37304cfd90b2631d188e76dd0dccbae/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishPlugin.kt#L75-L81)
* If so, it will return the `dokkaHtml` task (to generate the javadocs) otherwise it doesnt.

As the turbine project applies FIRST the multiplatform plugin, the action (from 1) will be executed. 
But at this time `dokka` is not YET applied (it will be applied after the multiplatform plugin), the plugins return `null` (== no javadoc generation).

To fix this, we can change the order of the applied plugins:
```diff
plugins {
+  alias(libs.plugins.dokka)
   alias(libs.plugins.kotlin)
   alias(libs.plugins.kotlinApiDump)
   alias(libs.plugins.spotless)
   alias(libs.plugins.publish)
-  alias(libs.plugins.dokka)
}
```

*However*, a few days ago a new release of the nexus plugin was prepared [See](https://github.com/vanniktech/gradle-maven-publish-plugin/commit/7bdff75b268a59e0dbea48095cb2f7bff2dc675b).

This changes this a bit and it seems it doesn't rely on the order of the plugins anymore.
Everything is now handeld in a `afterEvaluate` block (not the best solution IMHO, but 🤷 ).
See [this PR](https://github.com/vanniktech/gradle-maven-publish-plugin/pull/680) and espeically these locs:
* [Run stuff afterEvaluate](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/7bdff75b268a59e0dbea48095cb2f7bff2dc675b/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishPlugin.kt#L32-L35)
* [Check for applied plugins](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/7bdff75b268a59e0dbea48095cb2f7bff2dc675b/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt#L360)

So this issue is likely to be fixed with the next release of the nexus plugin 🙃

**Comment by JakeWharton** [comment]
Thanks for the analysis. Order definitely shouldn't matter so glad it's solved upstream.

**Comment by JakeWharton** [comment]
#288

**Comment by StefMa** [comment]
Did you tested it ? 😁

**Comment by JakeWharton** [comment]
Nope! You can check the snapshot if you want. I won't be at a computer for a while.

**Comment by StefMa** [comment]
Yep, it fixed it ✅ 
Tested it locally and the javadoc contains the dokka docs 🥳
