### ISSUE TITLE
compilation error Supertypes of the following classes cannot be resolved. 

### ISSUE THREAD

**Issue by danilshik** [cashapp/turbine#291]
A compilation error occurs when connecting the library:

`Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class kotlinx.coroutines.test.TestDispatcher, unresolved supertypes: kotlinx.coroutines.DelayWithTimeoutDiagnostics
Adding -Xextended-compiler-checks argument might provide additional information.`

testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$kotlin_coroutines_version"
testImplementation 'app.cash.turbine:turbine:1.0.0'

androidTestImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$kotlin_coroutines_version"
androidTestImplementation 'app.cash.turbine:turbine:1.0.0'

I've tried versions
kotlin_coroutines_version = 1.5.2 и 1.6.4

**Comment by JakeWharton** [comment]
We declare kotlinx.coroutines 1.7.1 as a dependency as noted in the release notes for 1.0: https://github.com/cashapp/turbine/releases/tag/1.0.0. Anything lower is likely to cause API mismatches.

Can you try 1.7.1?

**Comment by danilshik** [comment]
Downgraded the version to v0.12.3
