### ISSUE TITLE
Detected use of different schedulers - How to Resolve?

### ISSUE THREAD

**Issue by Egi10** [cashapp/turbine#301]
My function is like this:

```
interface A {
    fun testA(): Flow<String>
}

interface B {
    fun testB(): Flow<String>
}

class TestUseCase(
    private val a: A,
    private val b: B,
    private val coroutineDispatcher: CoroutineDispatcher
) {
    operator fun invoke(): Flow<String> {
        return a.testA().combine(
            b.testB()
        ) { a, b ->
            return@combine "$a + $b"
        }.flowOn(coroutineDispatcher)
    }
}
```

And I conduct unit tests like this:

```
class TestUseCaseTest : BaseTest() {
    @MockK
    lateinit var a: A

    @MockK
    lateinit var b: B

    @OptIn(ExperimentalCoroutinesApi::class)
    private val testUseCase by lazy {
        TestUseCase(
            a = a,
            b = b,
            coroutineDispatcher = UnconfinedTestDispatcher()
        )
    }

    @Test
    fun `test success`() = runTest {
        every {
            a.testA()
        } returns flowOf("a")

        every {
            b.testB()
        } returns flowOf("b")

        testUseCase.invoke().test {
            assertEquals("a + b", awaitItem())

            awaitComplete()
        }

        verify {
            a.testA()

            b.testB()
        }
    }
}
```
    
And I encounter this error:
```
Detected use of different schedulers. If you need to use several test coroutine dispatchers, create one `TestCoroutineScheduler` and pass it to each of them.
```

If I change `flowOn(coroutineDispatcher)` to `flowOn(Dispatchers.IO)`, it doesn't cause an error. How could this happen?

**Comment by JakeWharton** [comment]
This is not related to Turbine, but is an error from `runTest`. Your creation of `UnconfinedTestDispatcher` is divorced from the `TestCoroutineScheduler` in use by `runTest`. You need to look up the `TestCoroutineScheduler` inside the `coroutineContext` of `runTest` and supply it to the constructor of `UnconfinedTestDispatcher`.

**Comment by JakeWharton** [comment]
Turbine also uses `UnconfinedTestDispatcher`, and you can see we do the lookup and supply it to the constructor here:

https://github.com/cashapp/turbine/blob/87330c07cc80fc7e4fc165beec3343668bc25d8e/src/commonMain/kotlin/app/cash/turbine/flow.kt#L212-L213

**Comment by Egi10** [comment]
thanks @JakeWharton, solved issue
