### ISSUE TITLE
version 1.1.0 breaking dependencies

### ISSUE THREAD

**Issue by davexhardware** [cashapp/turbine#313]
I'm using the latest Turbine v1.1.0 in my gradle.build.kts ([pastebin](https://pastebin.com/jqnXuEfm)) with Gradle 8.4 and those settings in libs.versions.toml ([pastebin](https://pastebin.com/yysdPb2v)), so kotlin v1.8.20 and android gradle plugin v8.2.0
When I add the Turbine dependency in my commonTest.dependencie, some kotlin std lib dependencies, like kotlin.math and kotlin.ranges disappear and I get errors from everywhere. No idea of why that happens. Tried to downgrade to Kotlin v1.8.22 and Gradle 8.0 but I still get the same.
Solved downgrading to Turbine v1.0.0

**Comment by JakeWharton** [comment]
I've upgraded a bunch of open source and private projects (or, well, Renovate has) without incident. Can you make a minimally-reproducing project that I can try which exhibits the failure?

**Comment by davexhardware** [comment]
@JakeWharton Yes,and sorry for the wait. Try switching the turbine version in the gradle build file form 1.0.0 to 1.1.0
[MyApplicationTest.zip](https://github.com/cashapp/turbine/files/14742211/MyApplicationTest.zip)

**Comment by JakeWharton** [comment]
What command are you using to build. That project fails to compile regardless of the Turbine version given the `assemble` task.

**Comment by JakeWharton** [comment]
Going to close. Feel free to ping with an updated sample or more info if this is still a problem.
