### ISSUE TITLE
Recompile a new version with Kotlin 1.5.0

### ISSUE THREAD

**Issue by kozaxinan** [cashapp/turbine#36]
This is not a request before stable Kotlin but at the moment turbine doesn't work with kotlin 1.5.0-RC because of experimental time api changes. There is binary incompatibility between 1.4 and 1.5 about Duration class.

Issue reported to Kotlin and resolved as designed and suggested to build library with 1.5. 
https://youtrack.jetbrains.com/issue/KT-46254

**Comment by JakeWharton** [comment]
Yeah we're blocked by coroutines having a release to even upgrade the snapshot.

**Comment by JakeWharton** [comment]
Upstream tracking issue: https://github.com/Kotlin/kotlinx.coroutines/issues/2649

**Comment by JakeWharton** [comment]
The snapshot is now built against Kotlin 1.5 and coroutines 1.5-RC. We will wait for coroutines 1.5 stable before releasing.

**Comment by vRallev** [comment]
@JakeWharton Would you mind publishing a RC release and not just a snapshot? That would help a lot if it's not too much work.

**Comment by JakeWharton** [comment]
An appetizer while we collectively wait for the main course: https://github.com/cashapp/turbine/releases/tag/0.5.0-rc1

**Comment by JakeWharton** [comment]
https://github.com/Kotlin/kotlinx.coroutines/pull/2708

**Comment by JakeWharton** [comment]
https://github.com/cashapp/turbine/releases/tag/0.5.0
