### ISSUE TITLE
expectNoEvents() not working?

### ISSUE THREAD

**Issue by realdadfish** [cashapp/turbine#45]
I'm trying to test a Room Flow like the following:

```kotlin
 runBlocking {
    underTest.saveStuff(listOf(FIRST, SECOND)) // suspending DAO INSERT call

    roomExecutor.drain() // androidx.arch.core:core-testing's CountingTaskExecutorRule::drainTasks shortcut
    yield()

    underTest.observeStuff().test {
        assertThat(expectItem()).hasSize(2)
    }
}
```

Now when I execute this test, all is ok and green. But, to my surprise, if I verify like this

```kotlin
    underTest.observeStuff().test {
        expectNoEvents()
    }
```

the test won't fail either! I can even chain this and the test keeps green:

```kotlin
    underTest.observeStuff().test {
        expectNoEvents()
        assertThat(expectItem()).hasSize(2)
    }
```

How can it be that there are apparently no events verified, but if we look more closer, there are events? Can one rely at all on `expectNoEvents()`?

**Comment by JakeWharton** [comment]
`expectNoEvents()` onlly checks for events which have already been received and does not suspend waiting for any. When you call `expectItem()`, the test lambda suspends and allows other coroutines to run and emit. There is no way to assert that an event will never be emitted in the future since it's effectively impossible.

What would have helped make this more clear?

**Comment by realdadfish** [comment]
Coming from Rx my expectancy was that `expectNoEvents()` kind-of behaved like `assertNoValues()` of `TestSubscriber`, meaning that it would verify that it hasn't received any values _so far_, even though more could come through in the future.

Maybe I haven't read the documentation correctly, it stated

```
Assert that there are no unconsumed events which have been received.
```

which reads as if events have been captured "somehow", but weren't yet fetched via `expectItem`. Maybe another line for this specific method in the kdoc could make this more clear?

**Comment by JakeWharton** [comment]
I think we'll probably want to rename methods that suspend to be named differently than those which don't. #38 is adding another non-suspending one and unless you read the documentation carefully the distinction between the two is not obvious. Originally I think we used `await`-prefixed methods for suspending functions which more closely indicates their nature.
