### ISSUE TITLE
Unit' is only available since Kotlin 1.4.30 and cannot be used in Kotlin 1.4

### ISSUE THREAD

**Issue by irfanirawansukirman** [cashapp/turbine#53]
i'm using kotlin 1.4.21
corutines core & android 1.4.2

**Comment by JakeWharton** [comment]
Turbine uses coroutines 1.5.0 which presumably requires Kotlin 1.5.0 or newer.

That being said, there's not enough information to even discern what the error is so I'm just guessing based on what little you've provided.
