### ISSUE TITLE
Question: Is there a way to test no events emitted in the flow?

### ISSUE THREAD

**Issue by emartynov** [cashapp/turbine#58]
I have a function like:
```
val uiEvents = StateFlow<UIEvent>(Loading)

fun checkAppVersion() {
  viewModelScope.launch {
    val minRequiredAppVersion = repository.getRequireAppVerion()
    if (minRequiredAppVersion > currentAppVersion) {
      uiEvents.emit(ShowUpgradeDialog)
    }
  }
}
```

It was easy to test the case when there should be an upgrade event. 
I can not find a way how to test the case where is no upgrade situation. 

Later after the loading of the data UI state is changed to some data presentation. So I can check that `loading` changed to `data` state. But I wonder if there is a possibility to test this small bit that no events are passed to the flow?
Is it not an important test?

**Comment by JakeWharton** [comment]
You can assert that no events were received: https://cashapp.github.io/turbine/docs/0.x/turbine/app.cash.turbine/-flow-turbine/expect-no-events.html.

However, this function does not wait for anything and only asserts against events that were already received. So if you have something async you need to either delay or wait for a job to complete before calling it. Another way to put it is that this function does not assert that no events _will_ be received, merely that no events have already been received.

**Comment by emartynov** [comment]
Thank you for the answer!

The coroutines test is giving context that waits/finishes all launched jobs (if I'm not mistaken). Would it be possible to do something similar with Turbine? 

I see that the library is specifically testing flows. So this part I most probably need to write myself.

Thank you again!

**Comment by JakeWharton** [comment]
Turbine is not in control of any coroutine scopes so it has no facilities to do such a thing. Something to ensure a child scope is complete before asserting on emission is something that is left in your own hands.

**Comment by andrew-square** [comment]
That link originally posted is no longer available, but found it here. 

https://cashapp.github.io/turbine/docs/0.x/turbine/app.cash.turbine/expect-no-events.html

**Comment by hawklike** [comment]
The working link for the current library version:

https://cashapp.github.io/turbine/docs/1.x/-turbine/app.cash.turbine/expect-no-events.html
