### ISSUE TITLE
Kotlin 1.4 release

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/turbine#6]
Blocked on kotlinx.coroutines' 1.4 release

**Comment by hodgdon** [comment]
After updating to Kotlin 1.4, I am seeing a NoSuchMethod exception from expectItem()

> kotlin.time.Duration$Companion.getZERO()D
> java.lang.NoSuchMethodError: kotlin.time.Duration$Companion.getZERO()D
> 	at app.cash.turbine.ChannelBasedFlowTurbine.withTimeout(FlowTurbine.kt:190)
> 	at app.cash.turbine.ChannelBasedFlowTurbine.expectItem(FlowTurbine.kt:218)

According to a japi-compliance-checker diff of the stdlib:

> Removed from kotlin.time:
> Duration.Companion.getINFINITE ( )  :  double
> Duration.Companion.getZERO ( )  :  double

So I assume updating turbine to Kotlin 1.4 will fix this issue.

**Comment by JakeWharton** [comment]
It will, yes.
