### ISSUE TITLE
the library is not getting recognised in Intellij Idea

### ISSUE THREAD

**Issue by sushant-lendico** [cashapp/turbine#82]
If I put this jar in maven dependencies of spring boot-based normal kotlin application in IntelliJ idea, the jar is no more recognized.  Can it be available for normal kotlin projects as well?

**Comment by JakeWharton** [comment]
Is there a reason you're using a jar instead of a build tool that manages dependencies automatically such as Gradle or Maven?

Make sure you're using the turbine-jvm artifact if you're copying around .jar files: https://search.maven.org/artifact/app.cash.turbine/turbine-jvm/0.7.0/jar
