### ISSUE TITLE
Add skip functionality

### ISSUE THREAD

**Issue by JohannesPtaszyk** [cashapp/turbine#87]
Sometimes it might be good to have a way to skip a certain number of events to have a cleaner test without multiple await calls, which are then not part of any assertion. 
For my codebase I added an extension function like this: 
```
suspend fun <T> FlowTurbine<T>.skipItem(amount: Int = 1) = repeat(amount) {
    awaitItem()
}
```

Does it make sense to add that functionality on library level?

**Comment by JakeWharton** [comment]
Maybe? I'm trying to figure out if it is a useful API rather than just calling `repeat(5) { awaitItem() }`.

**Comment by JohannesPtaszyk** [comment]
I was also unsure if its worth or not. 
On the other hand: It feels and looks nicer within the test. 

Happy to discuss!

Edit: Another option would be to go with something like: 
``` 
public suspend fun awaitItems(count: Int): List<T>
```

But still unsure if its a nice thing to have or not.
For us the usecase was about skipping the first X events.

**Comment by JohannesPtaszyk** [comment]
I kept thinking about this for a while and it would be a good addition to explicitly add a skip or ignore function. 
It will highlight that we don't care about the X items, since they are not subject of what the test is trying to assert. 
Readability will be better and the intention of the author will also be easier to get. 
Also I think the benefit of ease of use outweighs the cost of the extra function.

**Comment by JakeWharton** [comment]
I'm okay with it if @MattPrecious is. Want to send a PR?

**Comment by mattprecious** [comment]
I think to make it a worthwhile addition over `repeat(5) { awaitItem() }`, there should be a helpful error message when it fails. Ex: `Expected 5 items, but got 4`, or `Expected 5 items, but got 4 and Error`. That's the kind of logic that I wouldn't want to repeat in all my tests.

**Comment by JohannesPtaszyk** [comment]
Will open a PR on the weekend, so it will be easier to have a base for further discussions.

**Comment by JohannesPtaszyk** [comment]
Not sure why the tests are not running on CI to be honest, since I they run fine locally for me. 
Would be glad to get a hint here. 
Currently building locally with JDK 17 on a Windows Intel maschine.
